<?php

namespace AppBundle\Repository;

/**
 * ParticipantEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantEvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEvent($id){
        $qb = $this->createQueryBuilder()
            ->select('l.valeurCompter)');

        return $qb->getQuery()
            ->getSingleScalarResult();



    }
}
